
1) From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
2) Replace missing values in Min.Price and Max.Price columns with their respective mean (check documentation).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
3) How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
4) Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays

# Q1

In [35]:
import pandas as pd
import numpy as np

In [ ]:
#filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0)

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [7]:
df_1 = df[['Manufacturer', 'Model' , 'Type']][:20]
df_1

Manufacturer       Model     Type
0         Acura     Integra    Small
1           NaN      Legend  Midsize
2          Audi          90  Compact
3          Audi         100  Midsize
4           BMW        535i  Midsize
5         Buick     Century  Midsize
6         Buick     LeSabre    Large
7         Buick  Roadmaster    Large
8         Buick     Riviera  Midsize
9      Cadillac     DeVille    Large
10     Cadillac     Seville  Midsize
11    Chevrolet    Cavalier  Compact
12    Chevrolet     Corsica  Compact
13    Chevrolet      Camaro   Sporty
14    Chevrolet      Lumina  Midsize
15    Chevrolet  Lumina_APV      Van
16    Chevrolet       Astro      Van
17    Chevrolet     Caprice    Large
18    Chevrolet    Corvette   Sporty
19          NaN    Concorde    Large

In [8]:
#Replace missing values in Min.Price and Max.Price columns with their respective mean (check documentation).

In [18]:
df_car = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df_car.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [31]:
df_car['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df_car['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
df_car.isnull().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              0
Price                  2
Max.Price              0
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [32]:
#How to get the rows of a dataframe with row sum > 100? 

In [37]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   29  30  23  22
1   12  32  35  23
2   26  25  27  30
3   28  21  22  26
4   27  37  17  30
5   11  34  39  29
6   19  11  27  26
7   12  39  12  24
8   10  22  19  29
9   19  25  23  12
10  30  20  30  26
11  21  22  28  22
12  33  22  22  34
13  33  24  32  30
14  39  12  11  16

In [53]:
df[df.sum(axis = 1) > 100]

0   1   2   3
0   29  30  23  22
1   12  32  35  23
2   26  25  27  30
4   27  37  17  30
5   11  34  39  29
10  30  20  30  26
12  33  22  22  34
13  33  24  32  30

In [ ]:
#reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. 
#Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, 
#and return the results as two separate NumPy arrays

In [59]:
array = np.random.randint(1,101,size=(4,4))
array

array([[40, 88, 47, 89],
       [82, 38, 26, 78],
       [73, 10, 21, 81],
       [70, 80, 48, 65]])

In [61]:
rows_array = arr.reshape(2, 8)
cols_array = arr.T.reshape(2, 8)
print(rows_array)
print(cols_array)

[[40 88 47 89 82 38 26 78]
 [73 10 21 81 70 80 48 65]]
[[40 82 73 70 88 38 10 80]
 [47 26 21 48 89 78 81 65]]


In [73]:
sum_row_col = lambda arr : np.array([np.sum(i) for i in arr])
print(sum_row_col(rows_array))
print(sum_row_col(cols_array))

[488 448]
[481 455]
