Using the glass.csv file on Github, answer the following questions

1)Try different thresholds for computing predictions using 'Al' column. By default it is 0.5. Use predict_proba function to compute probabilities and then try custom thresholds and see their impact on Accuracy, Precision and Recall.

2)Do the same analysis for other columns

3)Fit a Logistic Regression Model on all features. Remember to preprocess data(eg. normalization and one hot encoding).

### 1)Try different thresholds for computing predictions using 'Al' column.

In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

glass = pd.read_csv('glass.csv')
glass.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [113]:
glass.Type.value_counts().sort_index()

1    70
2    76
3    17
5    13
6     9
7    29
Name: Type, dtype: int64

In [114]:
glass.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

In [115]:
glass.isnull().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [116]:
glass['household'] = glass.Type.map({1:0, 2:0, 3:0, 5:1, 6:1, 7:1})
glass.household.value_counts()

0    163
1     51
Name: household, dtype: int64

In [117]:
glass

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type  household
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1          0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1          0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1          0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1          0
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1          0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...        ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7          1
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7          1
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7          1
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7          1
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7          1

[214 rows x 11 columns]

In [118]:
glass.sort_values( by = 'Al', inplace=True)
X = np.array(glass.Al).reshape(-1,1)
y = glass.household

In [119]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X,y)

LogisticRegression()

In [120]:
probabilities = logreg.predict_proba(X)
probabilities

array([[0.9939759 , 0.0060241 ],
       [0.99296771, 0.00703229],
       [0.98949363, 0.01050637],
       [0.98949363, 0.01050637],
       [0.98811597, 0.01188403],
       [0.98614074, 0.01385926],
       [0.98614074, 0.01385926],
       [0.98526292, 0.01473708],
       [0.9817376 , 0.0182624 ],
       [0.98117062, 0.01882938],
       [0.98058638, 0.01941362],
       [0.97806663, 0.02193337],
       [0.97738831, 0.02261169],
       [0.9752281 , 0.0247719 ],
       [0.9752281 , 0.0247719 ],
       [0.97367755, 0.02632245],
       [0.97286725, 0.02713275],
       [0.97203273, 0.02796727],
       [0.96937691, 0.03062309],
       [0.96843851, 0.03156149],
       [0.96843851, 0.03156149],
       [0.9643993 , 0.0356007 ],
       [0.9643993 , 0.0356007 ],
       [0.96331414, 0.03668586],
       [0.96219721, 0.03780279],
       [0.96104764, 0.03895236],
       [0.96104764, 0.03895236],
       [0.95986458, 0.04013542],
       [0.94755733, 0.05244267],
       [0.94755733, 0.05244267],
       [0.

In [121]:
# Store the predicted probabilities of class 1.
glass['household_pred_prob'] = probabilities[:, 1]

In [122]:
# Try different thresholds
from sklearn.metrics import accuracy_score, precision_score, recall_score
thresholds = [0.3, 0.4, 0.5, 0.6, 0.7]
for threshold in thresholds:
    # Predict using custom threshold
    y_pred = (probabilities[:, 1] > threshold).astype(int)
    
    # Calculate metrics
    accuracy = accuracy_score(y_true=y, y_pred=y_pred)
    precision = precision_score(y_true=y, y_pred=y_pred)
    recall = recall_score(y,pred)
    
    # Print results
    print(f"Threshold: {threshold}, Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}")

Threshold: 0.3, Accuracy: 0.8644859813084113, Precision: 0.72, Recall: 0.0
Threshold: 0.4, Accuracy: 0.8785046728971962, Precision: 0.8205128205128205, Recall: 0.0
Threshold: 0.5, Accuracy: 0.8691588785046729, Precision: 0.896551724137931, Recall: 0.0
Threshold: 0.6, Accuracy: 0.8411214953271028, Precision: 0.8695652173913043, Recall: 0.0
Threshold: 0.7, Accuracy: 0.8364485981308412, Precision: 1.0, Recall: 0.0


### 2)Do the same analysis for other columns

In [123]:
glass.sort_values( by = 'Mg', inplace=True)
X = np.array(glass.Mg).reshape(-1,1)
y = glass.household

In [124]:
logreg = LogisticRegression()
logreg.fit(X,y)
probabilities = logreg.predict_proba(X)
probabilities

array([[0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.14421094, 0.85578906],
       [0.

In [125]:
# Try different thresholds
from sklearn.metrics import accuracy_score, precision_score, recall_score
thresholds = [0.3, 0.4, 0.5, 0.6, 0.7]
for threshold in thresholds:
    # Predict using custom threshold
    y_pred = (probabilities[:, 1] > threshold).astype(int)
    
    # Calculate metrics
    accuracy = accuracy_score(y_true=y, y_pred=y_pred)
    precision = precision_score(y_true=y, y_pred=y_pred)
    recall = recall_score(y,pred)
    
    # Print results
    print(f"Threshold: {threshold}, Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}")

Threshold: 0.3, Accuracy: 0.9065420560747663, Precision: 0.7924528301886793, Recall: 0.0
Threshold: 0.4, Accuracy: 0.8785046728971962, Precision: 0.7659574468085106, Recall: 0.0
Threshold: 0.5, Accuracy: 0.8785046728971962, Precision: 0.7777777777777778, Recall: 0.0
Threshold: 0.6, Accuracy: 0.8785046728971962, Precision: 0.7777777777777778, Recall: 0.0
Threshold: 0.7, Accuracy: 0.8785046728971962, Precision: 0.7906976744186046, Recall: 0.0


In [126]:
glass.sort_values( by = 'Na', inplace=True)
X = np.array(glass.Na).reshape(-1,1)
y = glass.household

In [127]:
logreg = LogisticRegression()
logreg.fit(X,y)
probabilities = logreg.predict_proba(X)
probabilities

array([[0.99631667, 0.00368333],
       [0.99423634, 0.00576366],
       [0.99414677, 0.00585323],
       [0.99203461, 0.00796539],
       [0.98883109, 0.01116891],
       [0.98678055, 0.01321945],
       [0.97605579, 0.02394421],
       [0.96713859, 0.03286141],
       [0.96510842, 0.03489158],
       [0.95949088, 0.04050912],
       [0.9563665 , 0.0436335 ],
       [0.94941527, 0.05058473],
       [0.94142448, 0.05857552],
       [0.9405632 , 0.0594368 ],
       [0.93969007, 0.06030993],
       [0.93607623, 0.06392377],
       [0.93514173, 0.06485827],
       [0.93323449, 0.06676551],
       [0.93323449, 0.06676551],
       [0.93226145, 0.06773855],
       [0.93027583, 0.06972417],
       [0.92926294, 0.07073706],
       [0.92823648, 0.07176352],
       [0.92614221, 0.07385779],
       [0.92614221, 0.07385779],
       [0.92507411, 0.07492589],
       [0.92399183, 0.07600817],
       [0.92399183, 0.07600817],
       [0.92289523, 0.07710477],
       [0.92178414, 0.07821586],
       [0.

In [128]:
# Try different thresholds
from sklearn.metrics import accuracy_score, precision_score, recall_score
thresholds = [0.3, 0.4, 0.5, 0.6, 0.7]
for threshold in thresholds:
    # Predict using custom threshold
    y_pred = (probabilities[:, 1] > threshold).astype(int)
    
    # Calculate metrics
    accuracy = accuracy_score(y_true=y, y_pred=y_pred)
    precision = precision_score(y_true=y, y_pred=y_pred)
    recall = recall_score(y,pred)
    
    # Print results
    print(f"Threshold: {threshold}, Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}")

Threshold: 0.3, Accuracy: 0.8271028037383178, Precision: 0.625, Recall: 0.0
Threshold: 0.4, Accuracy: 0.8598130841121495, Precision: 0.7560975609756098, Recall: 0.0
Threshold: 0.5, Accuracy: 0.8551401869158879, Precision: 0.8571428571428571, Recall: 0.0
Threshold: 0.6, Accuracy: 0.822429906542056, Precision: 0.8823529411764706, Recall: 0.0
Threshold: 0.7, Accuracy: 0.8037383177570093, Precision: 1.0, Recall: 0.0


In [129]:
glass.sort_values( by = 'K', inplace=True)
X = np.array(glass.K).reshape(-1,1)
y = glass.household

In [130]:
logreg = LogisticRegression()
logreg.fit(X,y)
probabilities = logreg.predict_proba(X)
probabilities

array([[0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.77625796, 0.22374204],
       [0.

In [131]:
# Try different thresholds
from sklearn.metrics import accuracy_score, precision_score, recall_score
thresholds = [0.3, 0.4, 0.5, 0.6, 0.7]
for threshold in thresholds:
    # Predict using custom threshold
    y_pred = (probabilities[:, 1] > threshold).astype(int)
    
    # Calculate metrics
    accuracy = accuracy_score(y_true=y, y_pred=y_pred)
    precision = precision_score(y_true=y, y_pred=y_pred)
    recall = recall_score(y,pred)
    
    # Print results
    print(f"Threshold: {threshold}, Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}")

Threshold: 0.3, Accuracy: 0.7757009345794392, Precision: 1.0, Recall: 0.0
Threshold: 0.4, Accuracy: 0.7710280373831776, Precision: 1.0, Recall: 0.0
Threshold: 0.5, Accuracy: 0.7616822429906542, Precision: 0.0, Recall: 0.0
Threshold: 0.6, Accuracy: 0.7616822429906542, Precision: 0.0, Recall: 0.0
Threshold: 0.7, Accuracy: 0.7616822429906542, Precision: 0.0, Recall: 0.0


/Users/hengyi_wang/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/hengyi_wang/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/hengyi_wang/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### 3)Fit a Logistic Regression Model on all features.

In [132]:
glass

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type  \
184  1.51115  17.38  0.00  0.34  75.41  0.00  6.65  0.00  0.0     6   
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7   
180  1.51299  14.40  1.74  1.54  74.55  0.00  7.59  0.00  0.0     6   
190  1.51613  13.88  1.78  1.79  73.10  0.00  8.67  0.76  0.0     7   
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7   
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...   
163  1.51514  14.01  2.68  3.50  69.89  1.68  5.87  2.20  0.0     5   
185  1.51131  13.69  3.20  1.81  72.81  1.76  5.43  1.19  0.0     7   
201  1.51653  11.95  0.00  1.19  75.18  2.70  8.93  0.00  0.0     7   
172  1.51321  13.00  0.00  3.02  70.70  6.21  6.93  0.00  0.0     5   
171  1.51316  13.02  0.00  3.04  70.48  6.21  6.96  0.00  0.0     5   

     household  household_pred_prob  
184          1             0.007032  
212          1             0.508525  
180          1             0.229353  
190          1             0.393368  
211          1             0.570359  
..         ...                  ...  
163          1             0.992563  
185          1             0.408330  
201          1             0.090934  
172          1             0.967657  
171          1             0.969552  

[214 rows x 12 columns]

In [133]:
X = glass.drop(columns=['Type','household','household_pred_prob'])
y = glass.household

In [134]:
logreg = LogisticRegression()
logreg.fit(X,y)
probabilities = logreg.predict_proba(X)
probabilities

/Users/hengyi_wang/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[0.00459521, 0.99540479],
       [0.00527011, 0.99472989],
       [0.1463352 , 0.8536648 ],
       [0.25499526, 0.74500474],
       [0.00455168, 0.99544832],
       [0.58289993, 0.41710007],
       [0.0049078 , 0.9950922 ],
       [0.26659129, 0.73340871],
       [0.00370196, 0.99629804],
       [0.00443026, 0.99556974],
       [0.99382763, 0.00617237],
       [0.00346367, 0.99653633],
       [0.00297066, 0.99702934],
       [0.0020172 , 0.9979828 ],
       [0.30781392, 0.69218608],
       [0.00501347, 0.99498653],
       [0.00308239, 0.99691761],
       [0.95665733, 0.04334267],
       [0.0022077 , 0.9977923 ],
       [0.94027453, 0.05972547],
       [0.0790595 , 0.9209405 ],
       [0.76226803, 0.23773197],
       [0.99453693, 0.00546307],
       [0.59485838, 0.40514162],
       [0.00338409, 0.99661591],
       [0.00562394, 0.99437606],
       [0.88321485, 0.11678515],
       [0.00534719, 0.99465281],
       [0.0303587 , 0.9696413 ],
       [0.00361429, 0.99638571],
       [0.

In [135]:
# Try different thresholds
from sklearn.metrics import accuracy_score, precision_score, recall_score
thresholds = [0.3, 0.4, 0.5, 0.6, 0.7]
for threshold in thresholds:
    # Predict using custom threshold
    y_pred = (probabilities[:, 1] > threshold).astype(int)
    
    # Calculate metrics
    accuracy = accuracy_score(y_true=y, y_pred=y_pred)
    precision = precision_score(y_true=y, y_pred=y_pred)
    recall = recall_score(y,pred)
    
    # Print results
    print(f"Threshold: {threshold}, Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}")

Threshold: 0.3, Accuracy: 0.9345794392523364, Precision: 0.8363636363636363, Recall: 0.0
Threshold: 0.4, Accuracy: 0.9345794392523364, Precision: 0.8490566037735849, Recall: 0.0
Threshold: 0.5, Accuracy: 0.9345794392523364, Precision: 0.8775510204081632, Recall: 0.0
Threshold: 0.6, Accuracy: 0.9392523364485982, Precision: 0.9523809523809523, Recall: 0.0
Threshold: 0.7, Accuracy: 0.9392523364485982, Precision: 0.975, Recall: 0.0
